### ISSUE TITLE
Performance problems (module authenticates against crowd on each request)

### ISSUE THREAD

**Issue by fgimian** [kare/ngx_http_auth_crowd_module#4]
Hey there Kare, great job on this module for nginx! :smile: 

Once I started using it on our systems, I noticed it was significantly slower than the Apache module.  

After enabling debug on my crowd server and comparing the requests made vs the apache module, I realised that the reason the performance was worse was that an authentication request was sent for every single GET request against nginx.  Apache only seems to send one request to Crowd and then keeps the user logged in.

Is there any way to offer similar behaviour?

Here are the test results with 100 requests sent to our dashboard using various forms of authentication:

```
Atlassian Crowd (Nginx)   : 162.766 secs
Atlassian Crowd (Apache)  : 33.797 secs
No Authentication (Nginx) : 2.068 secs
```

Any help would be greatly appreciated, I really don't want to switch back to Apache :smile: 

Cheers
Fotis

**Comment by kare** [comment]
Module works as intended. It is stateless by design. You may consider a beefier auth server.

Cheers,
Kare
